In [21]:
import numpy as np
import random

%load_ext autoreload
%autoreload 2

In [4]:
    N = 20
    dimensions = [10, 5, 10]
    data = np.random.randn(N, dimensions[0])  # each row will be a datum
    labels = np.zeros((N, dimensions[2]))
    for i in range(N):
        labels[i, random.randint(0, dimensions[2] - 1)] = 1

    params = np.random.randn((dimensions[0] + 1) * dimensions[1] + (
            dimensions[1] + 1) * dimensions[2], )

In [6]:
data.shape

(20, 10)

In [22]:
from assignment1.q1_softmax import softmax

In [27]:
softmax(data).sum(axis=1)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
ex = np.exp(data)
sums = ex.sum(axis=1)
sums

array([ 16.99064267,  16.08363031,   7.69665904,  12.71287577,
         9.68491545,  19.52149013,  21.03178492,  14.38523829,
        14.24110662,  16.59169825,  17.57098878,  25.80688828,
        18.01487528,  11.06743306,  29.7333699 ,   9.54116146,
        14.05540793,  16.53827984,  11.90140579,  15.88546285])

In [12]:
np.multiply(ex, sums)

ValueError: operands could not be broadcast together with shapes (20,10) (20,) 

In [17]:
np.dot(ex.T, sums)

array([  698.42635066,   354.37654526,  1169.91574178,   413.33153941,
         417.33700806,   317.89568787,   877.79976637,   601.21146766,
         427.86006919,   354.24405162])

In [24]:
ex / sums[:,None]

array([[ 0.13749321,  0.1515125 ,  0.16807168,  0.05502915,  0.03842324,
         0.09328184,  0.07186788,  0.12720221,  0.02713035,  0.12998795],
       [ 0.2228302 ,  0.01362823,  0.34449848,  0.04057838,  0.0567988 ,
         0.04041139,  0.15021309,  0.10341426,  0.01900883,  0.00861835],
       [ 0.07689968,  0.0849382 ,  0.08171864,  0.08542371,  0.04309778,
         0.11073962,  0.26626881,  0.10955216,  0.05124495,  0.09011644],
       [ 0.06596288,  0.09691686,  0.20609593,  0.06576031,  0.03319227,
         0.05854551,  0.18496166,  0.10844468,  0.04720406,  0.13291584],
       [ 0.05966237,  0.03170285,  0.35338635,  0.08654355,  0.06810855,
         0.08484074,  0.18628363,  0.04278504,  0.06235928,  0.02432765],
       [ 0.13774853,  0.0251365 ,  0.12186038,  0.02806917,  0.03007844,
         0.05325864,  0.39998145,  0.12333917,  0.01169719,  0.06883052],
       [ 0.30966686,  0.02177259,  0.272292  ,  0.02460045,  0.03118405,
         0.02183125,  0.16021236,  0.06861456

In [30]:
np.reshape(range(18), (3,3,2)).shape

(3, 3, 2)

In [35]:
a = np.reshape(range(18), (3,3,2))

In [36]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [32]:
a * 2

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]],

       [[24, 26],
        [28, 30],
        [32, 34]]])

In [37]:
b = np.reshape(range(6), (3,2))
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [38]:
a * np.reshape(range(6), (3,2))

array([[[ 0,  1],
        [ 4,  9],
        [16, 25]],

       [[ 0,  7],
        [16, 27],
        [40, 55]],

       [[ 0, 13],
        [28, 45],
        [64, 85]]])

In [39]:
c = np.reshape(range(9), (3,3))

In [40]:
a * c

ValueError: operands could not be broadcast together with shapes (3,3,2) (3,3) 

In [43]:
c[:,:,None].shape

(3, 3, 1)

In [44]:
a * c[:,:,None]

array([[[  0,   0],
        [  2,   3],
        [  8,  10]],

       [[ 18,  21],
        [ 32,  36],
        [ 50,  55]],

       [[ 72,  78],
        [ 98, 105],
        [128, 136]]])

In [45]:
c[:,:,None]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [46]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
c[:,None]

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.ones((3,3), dtype=np.bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [53]:
arr = np.arange(18,shape=(3,3,2))

TypeError: 'shape' is an invalid keyword argument for this function

In [54]:
np.info("arange")

     *** Found in numpy ***
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use ``linspace`` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, t

In [55]:
np.info(np.mgrid)

`nd_grid` instance which returns a dense multi-dimensional "meshgrid".

An instance of `numpy.lib.index_tricks.nd_grid` which returns an dense
(or fleshed out) mesh-grid when indexed, so that each returned argument
has the same shape.  The dimensions and number of the output arrays are
equal to the number of indexing dimensions.  If the step length is not a
complex number, then the stop is not inclusive.

However, if the step length is a **complex number** (e.g. 5j), then
the integer part of its magnitude is interpreted as specifying the
number of points to create between the start and stop values, where
the stop value **is inclusive**.

Returns
----------
mesh-grid `ndarrays` all of the same dimensions

See Also
--------
numpy.lib.index_tricks.nd_grid : class of `ogrid` and `mgrid` objects
ogrid : like mgrid but returns open (not fleshed out) mesh grids
r_ : array concatenator

Examples
--------
>>> np.mgrid[0:5,0:5]
array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 

In [58]:
np.mgrid[0:3,0:3].shape

(2, 3, 3)

In [65]:
np.mgrid[0:3,0:3]

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [66]:
?np.ogrid


In [68]:
np.reshape(np.arange(9), (3,3)) % 2 == 0

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]], dtype=bool)

In [69]:
a = np.reshape(np.arange(9), (3,3))
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [70]:
a[a % 2 == 1] = -1

In [71]:
a

array([[ 0, -1,  2],
       [-1,  4, -1],
       [ 6, -1,  8]])

In [74]:
a = np.reshape(np.arange(9), (3,3))
out = a.copy()
out[a % 2 == 1] = -1

In [75]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
out

array([[ 0, -1,  2],
       [-1,  4, -1],
       [ 6, -1,  8]])

In [77]:
np.where(a % 2 == 1, -1, a)

array([[ 0, -1,  2],
       [-1,  4, -1],
       [ 6, -1,  8]])

In [78]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [79]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [80]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [82]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [83]:
np.info(np.r_)

Translates slice objects to concatenation along the first axis.

This is a simple way to build up arrays quickly. There are two use cases.

1. If the index expression contains comma separated arrays, then stack
   them along their first axis.
2. If the index expression contains slice notation or scalars then create
   a 1-D array with a range indicated by the slice notation.

If slice notation is used, the syntax ``start:stop:step`` is equivalent
to ``np.arange(start, stop, step)`` inside of the brackets. However, if
``step`` is an imaginary number (i.e. 100j) then its integer portion is
interpreted as a number-of-points desired and the start and stop are
inclusive. In other words ``start:stop:stepj`` is interpreted as
``np.linspace(start, stop, step, endpoint=1)`` inside of the brackets.
After expansion of slice notation, all comma separated sequences are
concatenated together.

Optional character strings placed as the first element of the index
expression can be used to change the ou

In [84]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [85]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [86]:
np.r_['-1',a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [87]:
a = np.array([1,2,3])

In [88]:
np.info(np.repeat)

 repeat(a, repeats, axis=None)

Repeat elements of an array.

Parameters
----------
a : array_like
    Input array.
repeats : int or array of ints
    The number of repetitions for each element.  `repeats` is broadcasted
    to fit the shape of the given axis.
axis : int, optional
    The axis along which to repeat values.  By default, use the
    flattened input array, and return a flat output array.

Returns
-------
repeated_array : ndarray
    Output array which has the same shape as `a`, except along
    the given axis.

See Also
--------
tile : Tile an array.

Examples
--------
>>> np.repeat(3, 4)
array([3, 3, 3, 3])
>>> x = np.array([[1,2],[3,4]])
>>> np.repeat(x, 2)
array([1, 1, 2, 2, 3, 3, 4, 4])
>>> np.repeat(x, 3, axis=1)
array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])
>>> np.repeat(x, [1, 2], axis=0)
array([[1, 2],
       [3, 4],
       [3, 4]])


In [89]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [91]:
np.repeat(np.arange(9).reshape((3,3)),3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7,
       7, 8, 8, 8])

In [92]:
np.repeat(np.arange(9).reshape((3,3)),3, axis=1)

array([[0, 0, 0, 1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4, 5, 5, 5],
       [6, 6, 6, 7, 7, 7, 8, 8, 8]])

In [93]:
np.repeat(np.arange(9).reshape((3,3)),3, axis=0)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [6, 7, 8],
       [6, 7, 8],
       [6, 7, 8]])

In [ ]:
a = 