In [1]:
import numpy as np
import random

%load_ext autoreload
%autoreload 2

In [ ]:
    N = 20
    dimensions = [10, 5, 10]
    data = np.random.randn(N, dimensions[0])  # each row will be a datum
    labels = np.zeros((N, dimensions[2]))
    for i in range(N):
        labels[i, random.randint(0, dimensions[2] - 1)] = 1

    params = np.random.randn((dimensions[0] + 1) * dimensions[1] + (
            dimensions[1] + 1) * dimensions[2], )

In [ ]:
data.shape

In [ ]:
from assignment1.q1_softmax import softmax

In [ ]:
softmax(data).sum(axis=1)

In [ ]:
ex = np.exp(data)
sums = ex.sum(axis=1)
sums

In [ ]:
np.multiply(ex, sums)

In [ ]:
np.dot(ex.T, sums)

In [ ]:
ex / sums[:,None]

In [ ]:
np.reshape(range(18), (3,3,2)).shape

In [ ]:
a = np.reshape(range(18), (3,3,2))

In [ ]:
a

In [ ]:
a * 2

In [ ]:
b = np.reshape(range(6), (3,2))
b

In [ ]:
a * np.reshape(range(6), (3,2))

In [ ]:
c = np.reshape(range(9), (3,3))

In [ ]:
a * c

In [ ]:
c[:,:,None].shape

In [ ]:
a * c[:,:,None]

In [ ]:
c[:,:,None]

In [ ]:
c

In [ ]:
c[:,None]

In [ ]:
np.arange(10)

In [ ]:
np.ones((3,3), dtype=np.bool)

In [ ]:
arr = np.arange(18,shape=(3,3,2))

In [ ]:
np.info("arange")

In [ ]:
np.info(np.mgrid)

In [ ]:
np.mgrid[0:3,0:3].shape

In [ ]:
np.mgrid[0:3,0:3]

In [ ]:
?np.ogrid


In [ ]:
np.reshape(np.arange(9), (3,3)) % 2 == 0

In [ ]:
a = np.reshape(np.arange(9), (3,3))
a[a % 2 == 0]

In [ ]:
a[a % 2 == 1] = -1

In [ ]:
a

In [ ]:
a = np.reshape(np.arange(9), (3,3))
out = a.copy()
out[a % 2 == 1] = -1

In [ ]:
a

In [ ]:
out

In [ ]:
np.where(a % 2 == 1, -1, a)

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [ ]:
a

In [ ]:
b

In [ ]:
np.vstack((a,b))

In [ ]:
np.info(np.r_)

In [ ]:
np.hstack([a,b])

In [ ]:
np.c_[a,b]

In [ ]:
np.r_['-1',a,b]

In [ ]:
a = np.array([1,2,3])

In [ ]:
np.info(np.repeat)

In [ ]:
np.repeat(a,3)

In [ ]:
np.repeat(np.arange(9).reshape((3,3)),3)

In [ ]:
np.repeat(np.arange(9).reshape((3,3)),3, axis=1)

In [ ]:
np.repeat(np.arange(9).reshape((3,3)),3, axis=0)

In [ ]:
a = 

In [2]:
import h5py


In [3]:
f= h5py.File("C:\\tmp\\weights.h5")

In [4]:
f.keys()

KeysView(<HDF5 file "weights.h5" (mode r+)>)

In [5]:
dset = f["L1Weights"]

In [6]:
dset.dtype

dtype('float64')

In [7]:
dset.shape

(3, 2)

In [8]:
dset[...]

array([[ 0.72715575, -0.57336414],
       [ 0.21650138, -0.6366607 ],
       [ 0.49030203,  0.45249012]])

In [11]:
f["L1Biases"][...]

array([ 0.,  0.,  0.])

In [12]:
f["L2Biases"][...]

KeyError: 'Unable to open object (address of object past end of allocation)'

In [13]:
f["L2Weights"]

KeyError: 'Unable to open object (len not positive after adjustment for EOA)'

In [14]:
f.close()

In [15]:
import os

In [16]:
os.unlink("C:\\tmp\\weights.h5")

In [17]:
del f

In [20]:
with h5py.File("C:\\tmp\\sample.h5") as f:
    print(f["L2Biases"][...])

[ 0.  0.  0.]


In [5]:
x = np.random.randn(12).reshape((4,3))

In [6]:
x

array([[ 0.34215638,  0.88494309,  0.02505803],
       [ 0.91003992,  0.77782513,  0.78177019],
       [-0.69169001, -0.20814893, -2.78752084],
       [ 0.64782554, -0.29958503,  0.23519574]])

In [11]:
xnorm = x / x.sum(axis=1)[:,None]

In [12]:
xnorm.sum(axis=1)

array([ 1.,  1.,  1.,  1.])

In [14]:
from assignment1.q3_word2vec import normalizeRows

ImportError: No module named 'q1_softmax'